devices:
  - address: 10.201.36.107
    username: admin
    password: C!sc0123
    os_type: nxos
    commands:
      - show version
      - show interface
      - show interface status
      - show interface trunk
      - show vlan
  - file: device-test.txt
    os_type: nxos
    commands:
      - show version
      - show interface status
      - show interface trunk
      - show vlan
      - show interface status
      - show ip route all